#!/bin/bash
#### USE THIS ONE ON OPHELIA 
## make sure to run in screen and to activate multiome_fin conda env

####Things for you to edit in the below block:
#sample names in the for sample in ....
#-d flag to the cellranger outs path
#-o flag to where you want the script to create a sample directory and write all outputs to
#-t the demuxlet temp directory, I basically just put -o path with demux_tmp at the end
#-v to where your contig ordered vcf file is
#optional: -g to a file with liver marker genes, don’t stress about this you can use the islet file I have listed but the plots autogenerated will look like shit because the markers are wrong but these are kinda intermediate plots you can totally remake correctly later

### run only R script 2 again with the corrected script
Bashscript_fp=/nfs/lab/rlmelton/scripts/multiome_pipeline_v4/github/multiome_sample_processing_v6_Sierra.sh
Command_list=multiome_sample_processing_v6_liver_pool_3_4_commands_list.txt

N=8

#Prep pool #3
for sample in QY_2380_2_QY_2379_2 QY_2382_2_QY_2381_2 QY_2384_1_2_QY_2383_1_2 QY_2386_2_QY_2385_2 QY_2388_2_QY_2387_2 QY_2390_2_QY_2389_2 QY_2392_2_QY_2391_2 QY_2394_1_2_QY_2393_1_2; do
        ((i=i%N)); ((i++==0)) && wait
        (
				#mkdir /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}
				#chmod 777 /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}
                                echo "bash $Bashscript_fp -s $sample -d /nfs/lab/projects/nash_nafld_liver/counts/${sample}/outs/ -r /home/rlmelton/.conda/envs/reticulate -o /nfs/lab/projects/nash_nafld_liver/sample_qc/ -t /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}/demux_tmp -v /nfs/lab/scorban/fnih_liver_47genotypes/47genotypes_trial2/topmed_imputed/FNIH_24_Liver_Pool_2_Batch_3_TOPMed_r209_maf01_catlas_1M_ordered_contig.vcf -m 500 -n 1000 -e 24 -g /nfs/lab/projects/nash_nafld_liver/sample_qc/240508_WE_liver_markers.txt > ${sample}.out" >> $Command_list


        ) &
done

#Prep pool #4
for sample in QY_2396_1_2_QY_2395_1_2 QY_2398_2_QY_2397_2 QY_2400_2_QY_2399_2 QY_2402_2_QY_2401_2 QY_2404_1_2_QY_2403_1_2 QY_2406_2_QY_2405_2 QY_2408_2_QY_2407_2 QY_2410_2_QY_2409_2; do
        ((i=i%N)); ((i++==0)) && wait
        (
				#mkdir /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}
				#chmod 777 /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}
                                echo "bash $Bashscript_fp -s $sample -d /nfs/lab/projects/nash_nafld_liver/counts/${sample}/outs/ -r /home/rlmelton/.conda/envs/reticulate -o /nfs/lab/projects/nash_nafld_liver/sample_qc/ -t /nfs/lab/projects/nash_nafld_liver/sample_qc/${sample}/demux_tmp -v /nfs/lab/scorban/fnih_liver_47genotypes/47genotypes_trial2/topmed_imputed/FNIH_23_Liver_Pool_Batch_4_TOPMed_r209_maf01_catlas_1M_ordered_contig.vcf -m 500 -n 1000 -e 23 -g /nfs/lab/projects/nash_nafld_liver/sample_qc/240508_WE_liver_markers.txt > ${sample}.out" >> $Command_list


        ) &
done
